export const metadata = {
  title: 'Alganews',
  description: 'Generated by Next.js',
  /* alternates: {
    canonical: '/'
  } */
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
