import Head from "next/head";
import FeaturedPost from "@/components/FeaturedPost";
import { Post, PostService } from "bigeus-sdk";
import { useEffect, useState } from "react";
import { GetServerSideProps } from "next";

interface HomeProps {
  posts: Post.Paginated
}

export default function Home(props: HomeProps) {
  const {posts} = props; 

  return (
    <div>
      <Head>
        <title>AlgaNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vector.png" />
      </Head>
      {
        posts?.content &&
        <FeaturedPost postSummary={posts?.content[0]} />
      }
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  context
) =>{
  const {page: _page} = context.query

  const page = Number(_page)
  
  if(isNaN(page)){
    context.res.statusCode = 302;
    context.res.setHeader("Location", "/?page=1") //keep the ""
  }

  const posts = await PostService.getAllPosts({page: Number(page) - 1})
  
  return {
    props: {
      posts
    }
  }
} 
