import Head from "next/head";
import FeaturedPost from "@/components/FeaturedPost";
import { Post, PostService } from "danielbonifacio-sdk-2";
import { GetServerSideProps } from "next";
import sendToHomePage from "@/core/utils/sendToHomePage";
import PostCard from "@/components/PostCard";
import PostsGrid from "@/components/PostsGrid";
import PageGrid from "@/components/PageGrid";
import ReactPaginate from "react-paginate";
import Router from "next/router";

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  { query, res }
) => {
  const { page: _page } = query

  const page = Number(_page);

  if (isNaN(page) || page < 1) {
    sendToHomePage(res);
  }

  const posts = await PostService.getAllPosts({ page: Number(page) - 1 })

  if (!posts.content?.length) {
    sendToHomePage(res);
  }

  return {
    props: {
      posts
    }
  }
}

interface HomeProps {
  posts: Post.Paginated
}

export default function Home(props: HomeProps) {
  const { posts } = props;

  return (
    <PageGrid>
      <Head>
        <title>AlgaNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vector.png" />
      </Head>
      {
        posts?.content && <FeaturedPost postSummary={posts?.content[0]} />
      }
      <PostsGrid>
        {
          posts.content?.slice(1).map(post => {
            return <PostCard key={post.id} post={post} />
          })
        }
      </PostsGrid>
      <ReactPaginate
        containerClassName={"Pagination"}
        pageCount={posts.totalPages || 0}
        marginPagesDisplayed={0}
        pageRangeDisplayed={3}
        previousLabel={"<"}
        nextLabel={">"}
        hrefBuilder={page => `/?page=${page}`}
        onPageChange={page => {
          Router.push(`/?page=${page.selected + 1}`)
        }}
      />
    </PageGrid>
  );
}

